export const CALL_API = 'CALL_API';
export const SET_STYLE = 'SET_STYLE';
export const SET_STYLE_SUCCEEDED = 'SET_STYLE_SUCCEEDED';
export const SET_CLIENT_SIZE = 'SET_CLIENT_SIZE';
export const SET_ACTIVE_QUERY_TAB = 'SET_ACTIVE_QUERY_TAB';
